//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ceny
    {
        public int Id { get; set; }
        public string Cena { get; set; }
    
        public virtual Rzeczy Rzeczy { get; set; }
        public virtual Uslugi Uslugi { get; set; }
        public virtual PozycjeZlecenia PozycjeZlecenia { get; set; }
    }
}
