//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaundryEntities : DbContext
    {
        public LaundryEntities()
            : base("name=LaundryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Things> Things { get; set; }
        public virtual DbSet<Zlecenia> ZleceniaSet { get; set; }
        public virtual DbSet<Wizyty> WizytySet { get; set; }
        public virtual DbSet<PozycjeZlecenia> PozycjeZleceniaSet { get; set; }
        public virtual DbSet<Ceny> CenySet { get; set; }
        public virtual DbSet<Uslugi> UslugiSet { get; set; }
        public virtual DbSet<Rzeczy> RzeczySet { get; set; }
    }
}
