//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderParts = new HashSet<OrderParts>();
        }
    
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string WorkerId { get; set; }
        public string GivingAddress { get; set; }
        public Nullable<System.DateTime> GivingDate { get; set; }
        public string ReceiveAddress { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderParts> OrderParts { get; set; }
    }
}
