//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjeZlecenia
    {
        public int Id { get; set; }
        public int Ilosc { get; set; }
        public int ZleceniaId { get; set; }
    
        public virtual Zlecenia Zlecenia { get; set; }
        public virtual Ceny Ceny { get; set; }
    }
}
