//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public int ThingId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Things Things { get; set; }
    }
}
